apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-healthfit-deployment
  labels:
    app: app-healthfit
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-healthfit
  template:
    metadata:
      labels:
        app: app-healthfit
    spec:
      containers:
      - image: aryadewangga/project:latest
        name: app-healthfit
        env:
          - name: "PORT"
            value: "8000"
          - name: "DRIVER"
            value: "mysql"
          - name: "ADDRESS"
            value: "database-1.c6hhzms8iiky.ap-southeast-1.rds.amazonaws.com"
          - name: "DB_PORT"
            value: "3306"
          - name: "USERNAME"
            value: "admin"
          - name: "PASSWORD"
            value: "aryadewangga"
          - name: "NAME"
            value: "app_fp"
          - name: "LOC"
            value: "Asia%2FJakarta"    
        ports:
           - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: go-app-service
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8000
  selector:
    app: app-healthfit
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: go-app-ingress
  annotations:
    dev.okteto.com/generate-host: "domain"
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: nginx-service
          servicePort: 8000