apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-fit-app-deployment
  labels:
    app: health-fit-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: health-fit-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: health-fit-app
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80