apiVersion: apps/v1
kind: Deployment
metadata:
      name: go-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
      - image: aryadewangga/fp-alta:latest
        name: go-app
        env:
          - name: "PORT"
            value: "8000"
          - name: "DRIVER"
            value: "mysql"
          - name: "ADDRESS"
            value: "database-1.c6hhzms8iiky.ap-southeast-1.rds.amazonaws.com"
          - name: "DB_PORT"
            value: "3306"
          - name: "USERNAME"
            value: "admin"
          - name: "PASSWORD"
            value: "aryadewangga"
          - name: "NAME"
            value: "app_fp"
          - name: "LOC"
            value: "Asia%2FJakarta"    
        ports:
           - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: go-app-service
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8000
  selector:
    app: go-app
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: go-app-ingress
  annotations:
    dev.okteto.com/generate-host: "domain"
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: go-app-service
          servicePort: 8080